#+PROPERTY: header-args:emacs-lisp :tangle ./init.el
* Header 
*Welcome To IDEmacs this custom configuration was created by Jachin Minyard in attempts to better understand Emacs, emacs-lisp and create an environment more along the lines of other IDE such as VS Code. Different aspects of the configuration are broken up into smaller sections below. Alot of the basis for my understanding of this material is due in part to the documentation but also the wonderful people over at !SystemCrafters! More features will continue to be added as I learn more about this enviroment. I hope you enjoy looking at my journey to master the Emacs environment*


* Package Management
Welcome to your first stop along the path to mastering Emacs configuration. There are many useful settings and configurations that come with Emacs by default, but in order to get the most out of it you should set up the package manager to make installing packages easier. The code in the following section seeks to do just that.

** Enable Packages
The following code segment enables package then adds several package directories to the package archives. This segment gives us access to packages from the following sites:

1. melpa
2. orgmode
3. elpa

Code:
#+begin_src emacs-lisp
  (require 'package)

  (setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("melpa" . "http://melpa.org/packages/")))

  (package-initialize)
#+end_src


** Initialize a New File 
The following segment is used to help initialize a new Emacs config file if none exist and no packages have been imported.

#+begin_src emacs-lisp
(unless package-archive-contents
  (package-refresh-contents))
#+end_src


** Use-Package
The following code segment is important as it allows for an easy way to configure packages you install by using the function *(use-package name)*. for more infromation on click here [[https://github.com/jwiegley/use-package/blob/master/README.md][(use-package)]].

*(setq use-package-always-ensure t)* is the equilivant to writing:

*(use-package name
       :ensure t)*

for all instances of *(use-package)*.

#+begin_src emacs-lisp
(require 'use-package)
(setq use-package-always-ensure t)
#+end_src


* UI Config
Welcome to the UI Config section. In this section you will find various packages and settings to alter the overall appearance of Emacs. This ranges from cleaning up the basic GUI window. To Changing the fonts and color schemes this is where you will find it.

** Disable Start Up Message
The start up message that Emacs displays can become very clutersome and can be better to just turn off all together. set the following value to 'nil' of you want to see the message 't' to turn it off.

#+begin_src emacs-lisp
;;Disables the startup message
(setq inhibit-startup-message t)
#+end_src


** GUI Config
The code provided below is used to set the opening window of the GUI
Along with the font and size of the font.
*** GUI Dimensions
By default a lot of systems will launch Emacs in this tiny window and you have to resize it every time. this setting can configure the size of the starting window to be something more manageable. we are going to start with the option to start all frames that get opened infull screen mode for now. 

- Notes:
  - Frames are the same things as a window if you are unfimilar with some of this teminology. 
  - you may need to check your .emacs file to make sure that the change is made when swapping between the settigs.

*(if (window-system) (set-frame-size (desired frame) width height))*
Width is measured in chars and height is measured in lines.
*(add-to-list 'initial-frame-alist '(fullscreen . maximized))*
changinf the 'initial-frame-alist -> 'default-frame-alist, you can change if just the initial frame opens in fullscreen or if all frames open in full screen.
#+begin_src emacs-lisp
;; Allows you to customize the size and width to great precision and which frame to modify.
;; (selected-frame) can be changed to the desired frame.
;; the two parameters after the frame selection are height and width respectivly
;; width is in characters and height is in lines.  
;;(if (window-system) (set-frame-size (selected-frame) 124 40))

;; If you dont care about tweaking the height and width the following commands will work just fine
;; uncomment this line to start the initial frame maximized
;;(add-to-list 'initial-frame-alist '(fullscreen . maximized))

;; uncomment this line to start every frame maximized
(add-to-list 'default-frame-alist '(fullscreen . maximized))

#+end_src

*** Text/Font
Code Will Set the Font and the font size. most people by default are used to font sizes like 12.0 13.0. this function takes font height as the size you want lets say 12.0 and accepts the parameter 12 * 100 = 120. Also keep in mind you may get an error when trying to set up the fonts as they might not be installed on your system. If that is the case just search the name of the font and how to install it. 

#+begin_src emacs-lisp
(set-face-attribute 'default nil :height 150)
;; Set the fixed pitch face
(set-face-attribute 'fixed-pitch nil :font "Fira Code Retina" :height 150)
;; Set the variable pitch face
(set-face-attribute 'variable-pitch nil :font "Cantarell" :height 170 :weight 'regular)
#+end_src

*** Line Numbers
In this section we will look at the line numbers on the left hand side of the screen and how to set it up globally and exclude modes where you do not what line numbers to appear.

**** Global Line Numbers

This code is increadibly simple. Enables line Numbers for all modes. Tho there are some modes where personaly I think the line numbers take away from the visual astetic of the mode *ie. org-mode*. So in the following section we will look at setting up an exclusion list tho there are some other implamentations that can be done here to avoid an exclusion list altogether.

This is the Global Line number code to turn the line numbers on everywhere.
#+begin_src emacs-lisp
;;Enables Global line numbers on the left side of the screen
(global-display-line-numbers-mode)
#+end_src

If you only want to turn line numbers on for spefic modes the following code will work better. This is just the reverse of what the code block for the exclusion block does and turns on line number mode for each of the following modes.
#+begin_src emacs-lisp
;; adds line numbers to the specified modes below. DO NOT USE IN CONJUNCTION WITH GLOBAL LINE MODE AND THE EXCLUSION LIST. pick one method or the other
;;(dolist (mode '(c-mode-hook
  ;;              c++-mode-hook
  ;;              java-mode-hook
  ;;              python-mode-hook))
  ;;(add-hook mode (lambda () (display-line-numbers-mode 1))))
#+end_src

**** Exclusion List for Line Numbers
This is the exclusion list if you chose to go with (global-display-line-numbers-mode) in the above section. If this is the case then you may find that some of the modes you come to work in do not need to have line numbers enabled. Personally I do not like the look of line numbers when I am working on my org documents so it has been turned off for that.

#+begin_src emacs-lisp
;;Creates Exclusion to remove certin modes from being effected by (global-display-line-numbers-mode)
(dolist (mode '(org-mode-hook
                term-mode-hook
                shell-mode-hook
                eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src


** Bar Modes
Welcome to Bar-Modes. This is one of the most basic features you can modify in the Emacs. All these options do are add additional GUI type features to the frames such as a scroll bar, menu bar, and tool bar. all features most GUI's have. Emacs gives you the ability turn these features on or off to give it a more sleek look. 

*** Tool-bar-mode
If you are new to Emacs and are not familiar with the basic key binds it is best to leave this one on. Enables the tool bar at the top of the GUI.. contains things like save, open, cut, paste...

#+begin_src emacs-lisp
;; Disables tool bar
(tool-bar-mode -1)
#+end_src

*** Menu-bar-mode
If you are new to Emacs and are not familiar with the basic key binds it is best to leave this one on. Enables the menu  bar at the top of the GUI.. contains things like Files, Tools, View,

#+begin_src emacs-lisp
;;Disables menu bar
(menu-bar-mode -1)
#+end_src

*** Scroll-bar-mode
This is one that is purely preference I turn the scroll bar off as it makes the screen less cluttered but leaving it on like everything in this document is purely optional based on the  users preference.

#+begin_src emacs-lisp
;;Disables scroll Bar
(scroll-bar-mode -1)
#+end_src


** Doom

*** Doom ModeLine
Description:
[[https://github.com/seagle0128/doom-modeline][Doom Modeline]]
Adds additional information to the Mode-Line and Provides and overhauled UI

This is our first look at an expanded version of the **(use-package)** function. Things to note are the **:init** section any code there will be run on initial start up. we place the command to enable doom Modeline there so it starts every time we open Emacs. There are many :Headers another one is **:custom** here we can place custom commands to edit the functionality of the package. there is also **:config**.  
#+begin_src emacs-lisp
(use-package doom-modeline
  :init
  (doom-modeline-mode 1)
  :custom
  ((doom-modeline-height 40)))
#+end_src

*** Doom Themes
Description:
[[https://github.com/doomemacs/themes][Doom Themes]]
Additional Color Schemes to add additional penalization to your config.

#+begin_src emacs-lisp
;;Installs the doom color themes
(use-package doom-themes)
#+end_src


** Color Themes
Everyone's favorite part the color theme! Change out the string 'doom-rouge to the theme of your choice. a full list of themes are listed below.

#+begin_src emacs-lisp
;;Sets the color theme
(load-theme 'doom-rouge t)
#+end_src

*** Default Themes
Themes that are installed with base Emacs.

**** Names
1. adwaita
2. deeper-blue
3. dichromacy
4. leuven
5. light-blue
6. manoj-dark
7. misterioso
8. tango
9. tango-dark
10. tsdh=dark
11. tsdh-light
12. wheatgrass
13. whiteboard
14. wombat

*** Doom Themes    
These are additional themes added by the [[https://github.com/doomemacs/themes/tree/screenshots][doom-themes]] package. Names of the themes listed below. (click the link to see screen shots)

**** Names
1. doom-1337
2. doom-Iosvkem
3. doom-acario-dark
4. doom-acario-light 
5. doom-ayu-dark 
6. doom-ayu-light 
7. doom-ayu-mirage 
8. doom-badger 
9. doom-bluloco-dark
10. doom-bluloco-light
11. doom-challenger-deep
12. doom-city-lights 
13. doom-dark+  
14. doom-dracula 
15. doom-earl-grey 
16. doom-ephemeral
17. doom-fairy-floss
18. doom-feather-dark
19. doom-feather-light
20. doom-flatwhite
21. doom-gruvbox-light
22. doom-gruvbox
23. doom-henna  
24. doom-homage-black 
25. doom-homage-white 
26. doom-horizon 
27. doom-ir-black 
28. doom-lantern 
29. doom-laserwave 
30. doom-manegarm 
31. doom-material-dark
32. doom-material
33. doom-meltbus 
34. doom-miramare
35. doom-molokai
36. doom-monokai-classic
37. doom-monokai-machine
38. doom-monokai-octagon 
39. doom-monokai-pro 
40. doom-monokai-ristretto
41. doom-monokai-spectrum 
42. doom-moonlight 
43. doom-nord-aurora 
44. doom-nord-light 
45. doom-nord 
46. doom-nova 
47. doom-oceanic-next
48. doom-oksolar-dark 
49. doom-oksolar-light
50. doom-old-hope 
51. doom-one-light
52. doom-one 
53. doom-opera-light
54. doom-opera 
55. doom-outrun-electric
56. doom-palenight 
57. doom-peacock 
58. doom-pine 
59. doom-plain-dark 
60. doom-plain 
61. doom-rouge 
62. doom-shades-of-purple 
63. doom-snazzy 
64. doom-solarized-dark-high-contrast
65. doom-solarized-dark
66. doom-solarized-light 
67. doom-sourcerer
68. doom-spacegrey 
69. doom-tokyo-night 
70. doom-tomorrow-day 
71. doom-tomorrow-nighte
72. doom-vibrant 
73. doom-wilmersdorf 
74. doom-xcode
75. doom-zenburn 

    
** Rainbow Delimiters
[[https://github.com/Fanael/rainbow-delimiters][Rainbow Delimiters]]
The following package is more of a utility package up since it changes the way delimiters appear in programming modes I decided to include it here. Rainbow Delimiters makes it so that matching delimiters will have the same color to make it easier to find matching parenthesis.

In this code block we get our first look at the **:hook** :header this allows you to set launch conditions for different packages based on the loading of a different package. In this code block we have **(prog-mode . rainbow-delimiters-mode)** this line state that if we are in a programming mode launch rainbow-delimiters-mode.
#+begin_src emacs-lisp
;;colors delimiters for easy matching
(use-package rainbow-delimiters
  :hook
  (prog-mode . rainbow-delimiters-mode))
#+end_src


* Org Mode
Welcome to [[https://orgmode.org/][Org Mode]]. This is one of the notable features about Emacs. While you can write org docs in other editors the full range of features is exclusive to Emacs. That being said lets dive into what org mode can do and the configuration required.

- This is where the code starts the become larger and more complicated in nature

** Font Configuration
First up lets look at seating up the text to be more pleasing when working on an org doc.

The following code snippet translates the base bullet point ' - ' and translates it into a nicer looking symbol in this case '•'. It also modifies the size of the headings based on the level in which it appears and makes sure that any features that require a fixed-face font are set to fixed-face. 

#+begin_src emacs-lisp
  (defun IDEmacs-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    ;; Set faces for heading levels
    ;;you can change the numerical value to change the size of the geading levels.
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "Cantarell" :weight 'regular :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil   :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-ofixed-pitch))
    (set-face-attribute 'org-checkbox nil :inherit '(fixed-pitch))
#+end_src



** Org Main Config
[[https://orgmode.org/manual/index.html][Org Mode Manual]] 
This is the main body of the code to set up Org mode. I tried to break up the configurations where I could. The user defined function *(defun IDEmacs-org-mode-setup)*  is where I placed all hooks and minor modes that I wished to launch along side org-mode. This includes an auto complete and a spell check. All additional configurations have been broken down into the features that they modify and been placed in user defined functions to make modifying your set up easier 

#+begin_src emacs-lisp
        (defun IDEmacs-org-mode-setup ()
          (org-indent-mode)
          (variable-pitch-mode 1)
          (visual-line-mode 1)
          (company-mode 1)
          (flyspell-mode 1))

        ;;Org-mode package and its built in configs
        (use-package org
          :hook 
          (org-mode . IDEmacs-org-mode-setup)
          (org-mode . IDEmacs-org-babel-tangle-config)
          :config
          (setq org-ellipsis " ")
          ;; User defined functions found below add to make the set up code look cleaner
          (IDEmacs-org-agenda-setup)
          (IDEmacs-org-custom-keywords)
          (IDEMacs-org-habits)
          (IDEmacs-org-task-refiling)
          (IDEmacs-org-capture-templates)
          (IDEmacs-font-setup))    
#+end_src

*** Custom Keywords
This User defined function sets up custom key word markers and tags that can be used through out org-mode and org-agenda.

#+begin_src emacs-lisp
(defun IDEmacs-org-custom-keywords ()
      (setq org-todo-keywords
            '((sequence "CURRENT(c)" " TODO(t)" "NEXT(n)" "|" "DONE(d!)")))

      ;;Creates a custom list of tags
      (setq org-tag-alist
            '((:startgroup)
              ;; Put mutually exclusive tags here
              (:endgroup)
              ("@errand" . ?E)
              ("@home" . ?H)
              ("@work" . ?W)
              ("agenda" . ?a)
              ("planning" . ?p)
              ("publish" . ?P)
              ("batch" . ?b)
              ("note" . ?n)
              ("idea" . ?i))))
#+end_src

*** Org Agenda 
set up for or-agenda. in this section we set up the path to specified file  or files that org-agenda will pull from as well as modifying the look of the log and the time before a task will show up on the agenda. Under all of that is some code to set up additional 

#+begin_src emacs-lisp
(defun IDEmacs-org-agenda-setup ()
      (setq org-agenda-files
            '("~/Documents/Projects/Code/Org-Mode/Schedule/Task.org")
            '("~/Documents/School/AssignmentSchedule.org"))
      (setq org-deadline-warning-days 7)
      (setq org-agenda-start-with-log-mode t)
      (setq org-log-done 'time)
      (setq org-log-into-drawer t)

      ;; Configure custom agenda views
      (setq org-agenda-custom-commands
            '(("d" "Dashboard"
               ((agenda "" ((org-deadline-warning-days 7)))
                (todo "NEXT"
                      ((org-agenda-overriding-header "Next Tasks")))
                (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))
	    
              ("n" "Next Tasks"
               ((todo "NEXT"
                      ((org-agenda-overriding-header "Next Tasks")))))
	    
              ("W" "Work Tasks" tags-todo "+work-email")

              ;; Low-effort next actions
              ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
               ((org-agenda-overriding-header "Low Effort Tasks")
                (org-agenda-max-todos 20)
                (org-agenda-files org-agenda-files))))))
#+end_src

*** Habit mode
Habit mode allows for additional task tracking 

#+begin_src emacs-lisp
  ;;Enables habit mode
  (defun IDEMacs-org-habits ()
    (require 'org-habit)
    (add-to-list 'org-modules 'org-habit)
    (setq org-habit-graph-column 60))
#+end_src

*** Refiling
allows the moving of completed task to an archive file to keep your task folder clean emacs will then save after a refiling.

#+begin_src emacs-lisp
  ;;Allows you to move completed task from the task file to the archive file
  (defun IDEmacs-org-task-refiling ()
    (setq org-refile-targets
          '(("Archive.org" :maxlevel . 1)
            ("Tasks.org" :maxlevel . 1)))
  
    ;; Save Org buffers after refiling!
    (advice-add 'org-refile :after 'org-save-all-org-buffers))

#+end_src

*** Capture templates
allows the binding of keys to allow quick access of files to do things like add a task, take a note, or look at some other code at a glance.

#+begin_src emacs-lisp
  (defun IDEmacs-org-capture-templates ()
    (setq org-capture-templates
          `(("t" "Tasks / Projects")
            ("tt" "Task" entry (file+olp "~/Documents/Projects/Code/Org-Mode/Schedule/Task.org" "Inbox")
             "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

            ("j" "Journal Entries")
            ("jj" "Journal" entry
             (file+olp+datetree "~/Documents/Projects/Code/Org-Mode/Schedule/Journal.org")
             "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
             ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
             :clock-in :clock-resume
             :empty-lines 1)
            ("jm" "Meeting" entry
             (file+olp+datetree "~/Documents/Projects/Code/Org-Mode/Schedule/Journal.org")
             "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
             :clock-in :clock-resume
             :empty-lines 1)

            ("w" "Workflows")
            ("we" "Checking Email" entry (file+olp+datetree "~/Documents/Projects/Code/Org-Mode/Schedule/Journal.org")
             "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1))))
#+end_src



** Heading Bullets  
Having * ** *** **** in your headings can become rather busy to look at to fix this problem we can use the package org-bullets this gives each level a unique symbol which you can then modify to your liking.

gets org-bullets and launches it anytime we enter org-mode. we then set the bullets to a custom list to keep a theme running in our files instead of letting the package auto assign symbols. If you wanna see what symbols the package will do natural remove the lines following *:custom*.
#+begin_src emacs-lisp
(use-package org-bullets
  :after org
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))
#+end_src




** Center Org Mode Buffers
Welcome to More formatting of text *YAY!*.  No for real tho in this section we have code that centers the org buffer on screen to make it closer to other document editorrs most people are familiar with. For more infromation on visual-fill-column click [[https://github.com/joostkremers/visual-fill-column][here]].

The following code block sets the size of the "margins", enables the centering of text, and enables column fill mode.
*(setq visual-fill-column-width VALUE)*
VALUE: set to an _number_ to change the width of the margins. I find the sweet spot for my devices is anywhere from 80-150. The Value is how many chars from the center you wish to start the text.
 *(visual-fill-column-center-text t)*
Should we center the test on the center column (_t or nil_)
*(visual-fill-column-mode 1)*
enables visual column-mode must set value to 1 _AND_ run in conjunction with *(visual-fill-column-center-text t)* to get text to center.
#+begin_src emacs-lisp
  (defun efs/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . efs/org-mode-visual-fill))
#+end_src



** Configure Babel Languages
[[https://orgmode.org/worg/org-contrib/babel/][org-babel]] allows for some awesome functionality with code blocks in org docs such as being able to evaluate and display the results of the code or writing the code to a separate source file as you develop. such as this file does with your Emacs config 

For more infromation on babel languages click [[https://orgmode.org/worg/org-contrib/babel/languages/index.html][here]]
#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)
     (C . t)
     (java .t)))
#+end_src



** Auto-tangle Configuration Files:
The point of this code is to let this file Auto-tangle with the .Emacs file. What this means is that this file when you save, it should automatically out-put the code blocks to the file specified in the header at the top of this file. For more infromation on tangle click [[https://orgmode.org/manual/Extracting-Source-Code.html][here]]

The following block defines a user function to run the tangle command after the buffer is saved. Every time we eval code to output it to the file named in the header of this file org-babel will ask if it is okay to eval this becomes a pain very quickly for large files so to turn this off we set *(org-confirm-babel-evaluate)* to nil.
#+begin_src emacs-lisp
  ;; Automatically tangle our Emacs.org config file when we save it
  (defun IDEmacs-org-babel-tangle-config ()
    (when (string-equal (buffer-file-name)
    (expand-file-name "~/Documents/Projects/Code/Org-Mode/IDEmacs/IDEmacs.org"))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'IDEmacs-org-babel-tangle-config)))
#+end_src



** Org Templates 
[[https://github.com/dangom/org-mode/blob/master/lisp/org-tempo.el][Org Tempo]] is a add on to org mode that extends the functionality of templates for code blocks. Below we set up a few templates to make inserting code blocks easier. to insert a code block for one of the languages below is simply type "<name" ie. "<el Tab" will insert a code block for emacs 

#+begin_src emacs-lisp
(require 'org-tempo)

(add-to-list 'org-structure-template-alist '("sh" . "src shell"))
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("j" . "src java"))
#+end_src


* Which Key
Which key is a helpful feature for all users but especially new users as it gives you a way to see what the options are for hot keys as you start typing the. Simply start the key bind sequence and scan the results to find the function. ie. type "C-c " this will pull up a mini window with the possible completions. 

#+begin_src emacs-lisp
  (use-package which-key
    :init
    (which-key-mode)
    :diminish
    which-key-mode
    :config
    (setq which-key-idle-delay 1))
#+end_src


* Spelling and Error Checking
Welcome to our Spelling and Error Checking for code and text file. This section will have a few different packages to help people who are new to development and are not sure of what functions they can use or what exactly the name of a header file is don't worry I have been there too.

** Flycheck
Welcome to [[https://www.flycheck.org/en/latest/][Flycheck]]! Flycheck is an Emacs package for on the fly syntax checking. This package combined with others can help make Emacs feel more like a complete IDE. Like any feature tho there maybe places where you prefer to have the feature turned off. to save you the hassle of having to turn off Flycheck manually just add the mode you wish to exclude to the Flycheck Exclusion List 

The following code block uses the package flycheck and the runs it anytime a program-mode is detected
#+begin_src emacs-lisp
  (use-package flycheck
    :hook
    (prog-mode . flycheck-mode))
#+end_src

*** Flycheck Exclusion List
Hopefully if you have been reading through this document the following code block should be familiar to you. just any modes to the mode '( ) that you wish to exclude from running Flycheck. 
#+begin_src emacs-lisp
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  eshell-mode-hook
                  emacs-lisp-mode-hook))
    (add-hook mode (lambda () (flycheck-mode 0))))
#+end_src


** Company
Welcome to  [[http://company-mode.github.io/][Company]] Mode. Company is a package that allows for auto completions as you work. This is a hand tool to have on as a newbie to a language as it can prompt you with options to help you ember functions you might have other wise forgot.
*** Company Mode
Company mode is a auto complete package for Emacs I use company mainly inside of programming languages to help me remember the full name of functions or other language specific features.

This code block enables company mode for all programming modes, org-mode as well,  and sets a few additional setting to make the experience of company more responsive.  *company-set-idle-delay* determines the time before the suggestions pop on screen. Where *company-minimum-prefix-length* determines the amount of chars you need before suggestions will appear on screen. 
#+begin_src emacs-lisp
  (use-package company
    :hook
    (prog-mode . company-mode)
    (org-mode . company-mode)
    :config
    (setq company-idle-delay 0.1)  
    (setq company-minimum-prefix-length 1))
#+end_src

*** Company Box Mode
 [[https://github.com/sebastiencs/company-box][Company-Box]] mode is an extension on Company-mode. This extension adds to addition functionality as well as cleans up the UI of the suggestions.

The hook in this code makes sure that if Emacs goes into Company-mode that company-box-mode will also launch.
#+begin_src emacs-lisp
(use-package company-box
  :hook
  (company-mode . company-box-mode))
#+end_src

*** Company Exclusion List
Hopefully if you have been reading through this document the following code block should be familiar to you. just any modes to the mode '( ) that you wish to exclude from running Company. I use company for most modes so for me this will be empty.

#+begin_src emacs-lisp
  ;;(dolist (mode '())
    ;;(add-hook mode (lambda () (company-mode 0))))
#+end_src


* Development
The Development section has packages that relate to the easy of use and work flow of coding projects that you might find useful. Projectile is a project manager, Magit is a git companion and Treemacs is a file display tree for easy project navigation.

** Treemacs
[[https://github.com/Alexander-Miller/treemacs][Treemacs]] is a file display system similar to something found in vs code. This is installed as a dependency of lsp-treemacs and all of its features. This package has some nice functionality and a large amount of customization's.

#+begin_src emacs-lisp
  (use-package treemacs
    :defer t
    :init
    (with-eval-after-load 'winum
      (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
    :config
    (treemacs-git-mode 'extended)
    (setq treemacs-width 20)
    (setq treemacs-indention 3)
    :bind
    ;; global map to pull up the currently displayed project.
    (:map global-map
          ("C-c q" . treemacs)))

  (use-package treemacs-projectile
    :after (treemacs projectile)
    :ensure t)

  (use-package treemacs-magit
    :after (treemacs magit)
    :ensure t)

#+end_src


** Projectile
[[https://docs.projectile.mx/projectile/index.html][Projectile]] is a local project manager. Determines if files in a directory are in a project such as directories that contain a .git or a .projectile. if it detects on of these files additional functionally becomes available such as replacing an instance of something across the whole project or jumping to files anywhere in the project directory.

The following code block dosent do much to change the base functionality of projectile we change the key binds to access projectile commands, define which auto complete to use and provide a path to where we store our git repositories. 

#+begin_src emacs-lisp
(use-package projectile
  :diminish
  projectile-mode
  :config
  ;; Turns on global projectile
  (projectile-mode)
  :custom
  ((projectile-completion-system 'company))
  :bind-keymap
  ;; Sets C-c p to open projectile commands
  ("C-c p" . projectile-command-map)
  :init
  ;; NOTE: Set this to the folder where you keep your Git repos!
  (when (file-directory-p "~/Documents/Projects/Code")
    (setq projectile-project-search-path '("~/Documents/Projects/Code")))
  (setq projectile-switch-project-action #'projectile-dired))
#+end_src


** Magit
 [[https://magit.vc/][Magit]] is a git companion. I have not made any customization's to this package and just use it at base. A quick run down of some of the commands first of open the magit buffer with "C-x g" This will open a new buffer with an over view of your current project now here's the kicker type h and it will give you a list of commands available. In the buffer some basic info such as staged and unstaged changes and recent commits should be shown. Some of these sections are collapsible this can be done with Tab. if you cursor over an unstaged file and type "s" you will stage that file. to unstage one select it and type "u". You can open the commit options by typing "c", and pushes can be done with "p". for more info on what is available check the documentation linked above.

#+begin_src emacs-lisp
(use-package magit)
#+end_src


** Lsp Mode
Welcome to the [[https://github.com/emacs-lsp/lsp-mode][lsp]] section. Lsp is a language server protocol that allows your editor access to a languages syntax such as java or c/c++. This package allows Emacs to have a more IDE like feel with error highlighting and info Boxes for different parts of the language.

*** Lsp Mode
The following section is the basic package for lsp-mode and some simple hook statements to help run it when a compatible program-mode is detected.

#+begin_src emacs-lisp
  (use-package lsp-mode
    :commands
    (lsp lsp-deferred)
    :hook
    (c-mode . lsp-mode)
    (c++-mode . lsp-mode)
    (python-mode . lsp-mode)
    :init
    (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
    :config
    (lsp-enable-which-key-integration t))
#+end_src


*** Lsp UI
lsp-ui adds additional features to the lsp library to allow for better customization's of lsp-mode. Note that all you need to do at base is call **(use-package)** lsp-ui.

#+begin_src emacs-lisp
  (use-package lsp-ui)
#+end_src


*** Lsp  Treemacs
Adds a unique file display tree for lsp-mode.

#+begin_src emacs-lisp
  (use-package lsp-treemacs
    :after lsp
    :config
    (lsp-treemacs-sync-mode 1)
    (setq lsp-treemacs-width 20)
    :bind 
    (:map global-map ("C-c t" . lsp-treemacs-symbols)))
#+end_src


*** Lsp Java
What is currently missing from using lsp-java mode.
#+begin_src emacs-lisp
(use-package lsp-java :config (add-hook 'java-mode-hook 'lsp))
(use-package helm-lsp)
(use-package helm
  :config (helm-mode))
#+end_src


** Dap
Dap is a debugger.

#+begin_src emacs-lisp
(use-package dap-mode :after lsp-mode :config (dap-auto-configure-mode))
(use-package dap-java :ensure nil)
#+end_src


* Key Bindings

** General Key-Binds

#+begin_src emacs-lisp
;;This is a useful keybind that allows ESC to exit out of prompts.
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src


** Projectile Key-Binds


** Org-Mode Key-Binds

#+begin_src emacs-lisp
  ;; Sets up Unique keybinds for Org-Mode  
  ;; Add entry to your journal
  (define-key global-map (kbd "C-c j")
    (lambda () (interactive) (org-capture nil "jj")))
  ;; set a todo task
  (define-key global-map (kbd "C-c l")
    (lambda () (interactive) (org-capture nil "tt")))
  ;; Open the Agenda.    
  (define-key global-map (kbd "C-c a")
    (lambda () (interactive) (org-agenda-list "a")))
#+end_src
