#+TITLE: IDEmacs
#+AUTHOR: Jachin Minyard

* Introduction
  IDEmacs is a collection of tools for Emacs that provide a more modern feel to Emacs. The current version of IDEmacs is 0.0.1 and focuses on the creation of an org files to store the task I deal with in my work flow. This version also includes a sidebar option that reads an org file that the user can populate with links to different files and views.

* Installation
  Download the files into a folder. add the folder to the Emacs load path. After this you can use require or use-package to load it.
** Requirements
   This Package requires the following packages to be installed:
   - org-super-agenda
   - org-modern
   - olivetti 
   - doct
   - nerd-icons
     - having a nerd font on your system is recommended for this package to work correctly.
     
* IDEmacs
  This is the main package and is in charge of setting up the IDEmacs-mode. This mode is a minor mode that wraps the other packages. While this package is not required to use the features found in the other packages. it helps link there functions together into a more cohesive configuration. idemacs-mode defines a keymap that can be used to set up Sudo global keybinds as idemacs-mode is a global mode and work in all buffers once it is activated.
** Variables
*** IDEmacs-theme
    This is the theme that is applied when idemas-mode is run.
    #+begin_src emacs-lisp
      (setq IDEmacs-theme 'candyLand)
    #+end_src    
*** IDEmacs-font-size
    This is the font size that is applied when idemas-mode is run.
    #+begin_src emacs-lisp
      (setq IDEmacs-font-size 120)
    #+end_src
*** Idemacs-line-numbers
    If t then line numbers are added to programing modes inside of IDEmacs.
    #+begin_src emacs-lisp
      (setq Idemacs-line-numbers t)
    #+end_src
*** IDEmacs-sidebar-on-startup
    If t then the sidebar is loaded when idemacs-mode is run.
    #+begin_src emacs-lisp
      (setq IDEmacs-sidebar-on-startup t)
    #+end_src
*** IDEmacs-agenda-on-startup
    If t then the agenda is loaded when idemacs-mode is run.
    #+begin_src emacs-lisp
      (setq IDEmacs-agenda-on-startup t)
    #+end_src
*** IDEmacs-mode-map
    This is the keymap that is used in idemacs-mode.
    #+begin_src emacs-lisp
      (define-key IDEmacs-mode-map (kbd "C-c C-s") 'idemacs/sidebar-open)
    #+end_src

* IDEmacs Orgfiles
  IDEmacs-orgfiles.el is a package that holds some custom variables to help with the creation of org files. The main function is the setting and the reformating of these org files. The org files defined by default are used in the IDEmacs-mode org-capture-template setup. This file contains several groups one for each of the default org files. This is to make it eaiser to customize the groups through the customize=group interface.
** Variables:
*** idemacs-personal-path
    This is the file and path to an org file that is used to store captured personal tasks. While you can use setq on this vaule it is recommended to set it using the idemacs/personal-set-path function.
*** idemacs-personal-template
    This is the initial sting that is written to the personal org file when it is created or reformated.
    #+begin_src emacs-lisp
	    (setq idemacs-personal-template
		  "#+CATEGORY: Personal\n\n* Projects\n* Family\n* Reminders\n* Goals\n")
    #+end_src
*** idemacs-home-path
    This is the file and path to an org file that is used to store captured home tasks. While you can use setq on this vaule it is recommended to set it using the idemacs/home-set-path function.
*** idemacs-home-template
    This is the initial sting that is written to the home org file when it is created or reformated.
    #+begin_src emacs-lisp
      (setq idemacs-home-template "#+CATEGORY: Home\n\n* Projects\n* Errands\n* Chores\n")
    #+end_src
*** idemacs-school-path
    This is the file and path to an org file that is used to store captured school tasks. While you can use setq on this vaule it is recommended to set it using the idemacs/school-set-path function.
*** idemacs-school-template
    This is the initial sting that is written to the school org file when it is created or reformated.
    #+begin_src emacs-lisp
	    (setq idemacs-school-template
		  "#+CATEGORY: School\n\n* Classes\n* Assignments\n* Projects\n* Exams\n* Labs\n")
    #+end_src
*** idemacs-refile--path
    This is the file and path to an org file that is used to store refiled tasks. While you can use setq on this vaule it is recommended to set it using the idemacs/personal-set-path function.
*** idemacs-refile-template
    This is the initial sting that is written to the refile org file when it is created or reformated.
    #+begin_src emacs-lisp
	    (setq idemacs-refile-template
		  "#+CATEGORY: Completed\n\n* School\n* Home\n* Personal\n* Work\n* Other\n")
    #+end_src
*** idemacs-agenda-file-list

** Functions:
*** idemacs/personal-set-path
    The idemacs/personal-set-path function is used to set the path to the personal org file. Use this over the standard setq. This function will create the file if it does not exisit and write the template to the file.
    #+begin_src emacs-lisp
      (idemacs/personal-set-path "~/.emacs.d/IDEmacs/OrgFiles/Personal.org")
    #+end_src
*** idemacs/personal-reformat-file
    The idemacs/personal-reformat-file function is used to reformat the personal org file. This function will write the template to the file.
*** idemacs/home-set-path
    The idemacs/personal-set-path function is used to set the path to the personal org file. Use this over the standard setq. This function will create the file if it does not exisit and write the template to the file.
    #+begin_src emacs-lisp
      (idemacs/home-set-path "~/.emacs.d/IDEmacs/OrgFiles/Home.org")
    #+end_src    
*** idemacs/home-reformat-file
    The idemacs/home-reformat-file function is used to reformat the home org file. This function will write the template to the file
*** idemacs/school-set-path
    The idemacs/school-set-path function is used to set the path to the school org file. Use this over the standard setq. This function will create the file if it does not exisit and write the template to the file.
    #+begin_src emacs-lisp
      (idemacs/school-set-path "~/.emacs.d/IDEmacs/OrgFiles/School.org")
    #+end_src
*** idemacs/school-reformat-path
    The idemacs/school-reformat-path function is used to reformat the school org file. This function will write the template to the file.
*** idemacs/refile-set-path
    The idemacs/refile-set-path function is used to set the path to the refile org file. Use this over the standard setq. This function will create the file if it does not exisit and write the template to the file.
    #+begin_src emacs-lisp
      (idemacs/refile-set-path "~/.emacs.d/IDEmacs/OrgFiles/Refile.org")
    #+end_src
*** idemacs/refile-reformat-file
    The idemacs/refile-reformat-file function is used to reformat the refile org file. This function will write the template to the file.
* IDEmacs Agenda
  IDEmacs-agenda.el is a package that customizes the org-agenda to have different views built to work with the org files created by IDEmacs-orgfiles.el. The main function is the creation of the different views that are used in the IDEmacs-mode, and the capturing of information to the org files.  
** Variables
*** idemacs--agenda-tag-list
    
** Functions
*** idemacs/view-daily-quest
*** idemacs/view-school-agenda
*** idemacs/view-agenda
*** idemacs/capture-school-class
*** idemacs/capture-sidebar-entries

* IDEmacs Sidebar
** Variables
*** idemacs-sidebar-file
*** idemacs-sidebar-template
*** idemacs-sidebar-link-name
*** idemacs-sidebar-width
*** idemacs-sidebar-lighter

** Functions
*** idemacs/sidebar-set-path
*** idemacs/sidebar-reformat-file
*** idemacs/sidebar-open
*** idemacs/sidebar-toggle
*** idemacs/sidebar-insert-link
