#+TITLE: IDEmacs
#+AUTHOR: Jachin Minyard

* Introduction
  
* Installation
  Download the files into a directory of your chosing. After that add the following code to your configuration file:
  #+begin_src elisp
    (require 'package)
    (setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
			     ("org" . "https://orgmode.org/elpa/")
			     ("melpa" . "http://melpa.org/packages/")))

    (package-initialize)

    (use-package IDEmacs
      :load-path "~/Documents/IDEmacs/IDEmacs-0.0.1/"
      :config
      (idemacs/personal-set-path idemacs-personal-default-path)
      (idemacs/school-set-path idemacs-school-default-path)
      (idemacs/home-set-path idemacs-home-default-path)
      (idemacs/refile-set-path idemacs-refile-default-path)
      (idemacs/sidebar-set-path idemacs-sidebar-file-default))

  #+end_src
  This is the bare minimum needed to get the package set up. DONT FORGET TO SET THE CORRECT LOAD-PATH! The load path should be the path to the directory that contains the IDEmacs files. The idemacs/personal-set-path, idemacs/school-set-path, idemacs/home-set-path, idemacs/refile-set-path, and idemacs/sidebar-set-path functions are used to set and create the org files. The default paths can be replaced with a path of your choosing.

  To access idemacs-mode type M-x RET idemacs-mode. Or use the hotkey <F2>.
     
* IDEmacs
  This is the main package and is in charge of setting up the IDEmacs-mode. This mode is a minor mode that wraps the other packages. While this package is not required to use the features found in the other packages. it helps link there functions together into a more cohesive configuration. idemacs-mode defines a keymap that can be used to set up Sudo global keybinds as idemacs-mode is a global mode and work in all buffers once it is activated.
** Variables
*** IDEmacs-theme
    This is the theme that is applied when idemas-mode is run.
    #+begin_src emacs-lisp
      (setq IDEmacs-theme 'wombat)
    #+end_src    

*** IDEmacs-font-size
    This is the font size that is applied when idemas-mode is run.
    #+begin_src emacs-lisp
      (setq IDEmacs-font-size 120)
    #+end_src

*** Idemacs-line-numbers
    If t then line numbers are added to programing modes inside of IDEmacs.
    #+begin_src emacs-lisp
      (setq Idemacs-line-numbers t)
    #+end_src

*** IDEmacs-sidebar-on-startup
    If t then the sidebar is loaded when idemacs-mode is run.
    #+begin_src emacs-lisp
      (setq IDEmacs-sidebar-on-startup t)
    #+end_src

*** IDEmacs-agenda-on-startup
    If t then the agenda is loaded when idemacs-mode is run.
    #+begin_src emacs-lisp
      (setq IDEmacs-agenda-on-startup t)
    #+end_src

*** IDEmacs-mode-map
    This is the keymap that is used in idemacs-mode.
    #+begin_src emacs-lisp
      (define-key IDEmacs-mode-map (kbd "C-c C-s") 'idemacs/sidebar-open)
    #+end_src
    
* IDEmacs Orgfiles
  IDEmacs-orgfiles.el is a package that holds some custom variables to help with the creation of org files. The main function is the setting and the reformating of these org files. The org files defined by default are used in the IDEmacs-mode org-capture-template setup. This file contains several groups one for each of the default org files. This is to make it eaiser to customize the groups through the customize-group interface.
** Variables:
*** idemacs-personal-path
    This is the file and path to an org file that is used to store captured personal tasks. While you can use setq on this vaule it is recommended to set it using the idemacs/personal-set-path function.

*** idemacs-personal-template
    This is the initial sting that is written to the personal org file when it is created or reformated.
    #+begin_src emacs-lisp
	    (setq idemacs-personal-template
		  "#+CATEGORY: Personal\n\n* Projects\n* Family\n* Reminders\n* Goals\n")
    #+end_src

*** idemacs-home-path
    This is the file and path to an org file that is used to store captured home tasks. While you can use setq on this vaule it is recommended to set it using the idemacs/home-set-path function.

*** idemacs-home-template
    This is the initial sting that is written to the home org file when it is created or reformated.
    #+begin_src emacs-lisp
      (setq idemacs-home-template "#+CATEGORY: Home\n\n* Projects\n* Errands\n* Chores\n")
    #+end_src

*** idemacs-school-path
    This is the file and path to an org file that is used to store captured school tasks. While you can use setq on this vaule it is recommended to set it using the idemacs/school-set-path function.

*** idemacs-school-template
    This is the initial sting that is written to the school org file when it is created or reformated.
    #+begin_src emacs-lisp
	    (setq idemacs-school-template
		  "#+CATEGORY: School\n\n* Classes\n* Assignments\n* Projects\n* Exams\n* Labs\n")
    #+end_src

*** idemacs-refile--path
    This is the file and path to an org file that is used to store refiled tasks. While you can use setq on this vaule it is recommended to set it using the idemacs/personal-set-path function.

*** idemacs-refile-template
    This is the initial sting that is written to the refile org file when it is created or reformated.
    #+begin_src emacs-lisp
	    (setq idemacs-refile-template
		  "#+CATEGORY: Completed\n\n* School\n* Home\n* Personal\n* Work\n* Other\n")
    #+end_src

*** idemacs-agenda-file-list

** Functions:
*** idemacs/personal-set-path
    The idemacs/personal-set-path function is used to set the path to the personal org file. Use this over the standard setq. This function will create the file if it does not exisit and write the template to the file.
    #+begin_src emacs-lisp
      (idemacs/personal-set-path "~/.emacs.d/IDEmacs/OrgFiles/Personal.org")
    #+end_src

*** idemacs/personal-reformat-file
    The idemacs/personal-reformat-file function is used to reformat the personal org file. This function will write the template to the file.

*** idemacs/home-set-path
    The idemacs/personal-set-path function is used to set the path to the personal org file. Use this over the standard setq. This function will create the file if it does not exisit and write the template to the file.
    #+begin_src emacs-lisp
      (idemacs/home-set-path "~/.emacs.d/IDEmacs/OrgFiles/Home.org")
    #+end_src    

*** idemacs/home-reformat-file
    The idemacs/home-reformat-file function is used to reformat the home org file. This function will write the template to the file

*** idemacs/school-set-path
    The idemacs/school-set-path function is used to set the path to the school org file. Use this over the standard setq. This function will create the file if it does not exisit and write the template to the file.
    #+begin_src emacs-lisp
      (idemacs/school-set-path "~/.emacs.d/IDEmacs/OrgFiles/School.org")
    #+end_src

*** idemacs/school-reformat-path
    The idemacs/school-reformat-path function is used to reformat the school org file. This function will write the template to the file.

*** idemacs/refile-set-path
    The idemacs/refile-set-path function is used to set the path to the refile org file. Use this over the standard setq. This function will create the file if it does not exisit and write the template to the file.
    #+begin_src emacs-lisp
      (idemacs/refile-set-path "~/.emacs.d/IDEmacs/OrgFiles/Refile.org")
    #+end_src

*** idemacs/refile-reformat-file
    The idemacs/refile-reformat-file function is used to reformat the refile org file. This function will write the template to the file.
* IDEmacs Agenda
  IDEmacs-agenda.el is a package that customizes the org-agenda to have different views built to work with the org files created by IDEmacs-orgfiles.el. The main function is the creation of the different views that are used in the IDEmacs-mode, and the capturing of information to the org files.  
** Variables
*** idemacs--agenda-tag-list
    This is a list of tags that are added to the list of tags that are used in the agenda views. It can be set in the following way:
    #+begin_src emacs-lisp
	    (setq idemacs--agenda-tag-list '(("name" . ?n)
					     ("work" . ?w)))
    #+end_src
    
** Functions
*** idemacs/view-daily-quest
    This function will pull up an agenda view in which the users daily tasks are displayed.
*** idemacs/view-school-agenda
    This function will pull up an agenda view in which the users school tasks are displayed. 
*** idemacs/view-agenda
    This function will pull up an agenda view in which general task are displayed.
*** idemacs/capture-school-class
    This function will capture a school class and add it to the school org file.
*** idemacs/capture-sidebar-entries
    This function will capture a sidebar entry and add it to the sidebar org file.
    
* IDEmacs Sidebar
  The emacs side bar is a window that holds links to different files and agenda views. it acts as a mini planner that can be used to navigate to different parts of the users workflow. At the current state the user is responsiable for populating the org file with links tho I have provided a few links to get the user started.
** Variables
*** idemacs-sidebar-file
    This is the file and path to an org file that is used to store sidebar links. While you can use setq on this vaule it is recommended to set it using the idemacs/sidebar-set-path function.
    
*** idemacs-sidebar-template
    This is the sting that will be written to the sidebar file when it is created or reformated.
    #+begin_src emacs-lisp
      (setq idemacs-sidebar-template
	    "* Schedules:\n [[sidebar:daily-agenda][Daily Quest]]\n [[sidebar:school-agenda][School Agenda]]\n\n* Config\n [[IDEmacs_file:~/.emacs.d/init.el][Init File]]\n")
    #+end_src
    
*** idemacs-sidebar-link-name
    This can be set to change the name of the link type. That would be in '[[link-type:query|files|format] [name]]'
    #+begin_src emacs-lisp
      (setq idemacs-sidebar-link-name "sidebar")
    #+end_src

*** idemacs-sidebar-width
    
    Determines how wide the sidebar will be.
    #+begin_src emacs-lisp
      (setq idemacs-sidebar-width 30)
    #+end_src

*** idemacs-sidebar-lighter
    Determines the lighter for the sidebar. A lighter is the symbol that shows up on the mode line to determine which minor modes are active.
    #+begin_src emacs-lisp
      (setq idemacs-sidebar-lighter " Sidebar")
    #+end_src

** Functions
*** idemacs/sidebar-set-path
    The idemacs/sidebar-set-path function is used to set the path to the sidebar org file. Use this over the standard setq. This function will create the file if it does not exisit and write the template to the file.
    #+begin_src emacs-lisp
      (idemacs/sidebar-set-path "~/.emacs.d/IDEmacs/OrgFiles/Sidebar.org")
    #+end_src

*** idemacs/sidebar-reformat-file
    This function will wipe the sidebar file so be careful when using it. After the file has been wipped it will have the idemacs-sidebar-template written to it.
*** idemacs/sidebar-open
    This opens the sidebar and enables idemacs-sidebar-mode.
*** idemacs/sidebar-toggle
    Turns the sidebar on and off.
*** idemacs/sidebar-insert-link
    Inserts a new link below the pont.
